/*
 * This Java source file was generated by the Gradle 'init' task.
*/
package lab01.richard.group04.a1;

// public class App {
//     public String getGreeting() {
//         return "Hello World!";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }

import java.util.Scanner;
public class App {
    public void getGreeting() {
          
        System.out.println("\nWELCOME TO ASHES!\n");
        return;
    }

    public static void main(String[] args) {
        new App().getGreeting();
        System.out.print("Do you want to register or login now?: ");
        Scanner scanner = new Scanner(System.in);
        String loginChoice = scanner.nextLine();
        while(true){
            if ("login".equalsIgnoreCase(loginChoice)) {
               
                Login.main(null);
            }
            else if ("register".equalsIgnoreCase(loginChoice)) {
                
                RegistrationApp.main(null);
            }
            else if ("exit".equalsIgnoreCase(loginChoice)) {
                
                break;
            }
        }
        scanner.close();
}
}
