/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab01.richard.group04.a1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   
}
FooterThe University of Sydney
The University of Sydney
